### ISSUE TITLE
CD Player runs only in demo mode because of MSDCEX is missing.

### ISSUE THREAD

**Issue by rabe-soft** [bluewaysw/pcgeos#355]
![cd-player](https://github.com/bluewaysw/pcgeos/assets/45405983/1d0bf09c-c71b-48ce-9808-f04007693438)

**Comment by lockesoft66** [comment]
And I always think it's a bug in my configuration. :-)

Und ich denke immer, dass es ein Fehler in meiner Konfiguration ist. :-)

**Comment by nschulux** [comment]
In der CONFIG.SYS 
device=oakcdrom.sys /D:mscd001 
devicehigh=ramdrive.sys /E 2048
Und in der AUTOEXEC.BAT
MSCDEX.EXE /D:mscd001 /L:%CDROM%
Ich glaube nicht dass das unter Dosbox geht.
Besser wäre Music Player gabs anscheinend von GlobalPC ich hatte hier im Repro eine Help Datei MUSICPLA.000 gesehen aber keinen Code.

**Comment by lockesoft66** [comment]
Guck ich mir die Tage an, ob das was bringt.
Die bootmeldung von Dosbox sagt jedenfalls, das Mscdex geladen wird. Die Version müsste ich gucken, weiss ich grad nicht.
In meinem Fall könnt es aber auch noch was ganz anderes sein.
Ich hab Zwei Laufwerke.
Ein BlueRay- und ein Dvd-Brenner.
mit dem Parameter "usecd=1" oder so (sitze grad nicht vorm PC) meckert Geos immerhin schon mal nicht, dass keine CD eingelegt ist.
mir wird der Name der CD angezeigt, wenn ich auf das CD-Icon klicke und ansonsten ein leeres Fenster.
Keine Ahnung, wo es hakt.
Das Laufwerk?
Debian Linux?
Die Dosbox-Staging / basebox?
Oder vielleicht doch in PC/Geos?....

**Comment by lockesoft66** [comment]
Now, i can use the CD-Rom-Drive in Datamode. Still only one of Two. But it works.
The Use of Parameter for cdroms is optional

The solution is / was a special Feature of Debian-Linux. Debian mount the CD-Rom not at /Media/cdrom. 
Debian mount them in an special SubDirectory   with the Name of User in  /Media .
But Debian mount removable Media like USB-Stick there too. If You use CD-Rom-Parameters, the mounted Drive works only still an CD-Rom is inserted. Otherwise, without these Parameters You get only an empty Directory.

Nun das ganze nochmal in Deutsch. :-)
Jetzt kann ich mein CD-Rom schonmal im Datenmodus nutzen. Immer noch nur eins von den beiden, aber es klappt.
Die Benutzung der CD-Rom typischen Parameter ist dabei optional.

Die Lösung ist / war, dass Debian Linux CD-Roms nicht in /media/cdrom mounted sondern on einem 
Verzeichnis mit dem namen des Benutzer in /media einhängt.
Aber Debian mountet auch alle anderen austauschbaren Medien in diesem Verzeichnis.
Wenn Ihr also die CD-Rom typischen Parameter der Dosbox nutzt funktioniert das Ganze nur, wenn auch eine CD Im Laufwerk ist. Ohne bekommt Ihr nur ein leeres Verzeichnis angezeigt.

**Comment by rabe-soft** [comment]
The problem still persists if the CD is mouted (in fact it is a blu ray writer). 
![cdrom](https://github.com/bluewaysw/pcgeos/assets/45405983/4dc562b9-1c73-44c2-9e13-959444156e01)
GeoManager recognizes a CD drive, but cannot find any disk in it.
If I mount without -t cdrom I can access the CD in data mode.

**Comment by lockesoft66** [comment]
Audio-CD still does not work.

For Datamode:
The BlueRay-Player Writer does not work her too. Only the DVD-Writer works.
in Linux every thing is a file :-) Maybe thats the Reason why i Don´t have to use the cdrom parameters in Dosbox.

Audio-CD klappt hier nach wie vor nicht
Bei den DatenCDs:
Der BluRaybrenner klappt gar nicht. Nur der DVD-Brenner funktioniert.
In Linux ist dem Motto nach alles eine Datei. Vielleicht ist das der Grund warum das hier auch ohne die cdromParameter der Dosbox geht.

**Comment by coldacid** [comment]
Similar problem using NWCDEX that comes with Novell DOS 7.0. It should provide everything that MSCDEX 2.1 provides, and more, but CD Player doesn't know or care about it.

**Comment by coldacid** [comment]
I just took a look at `MSCDEX_Get_Version()` in [cdaudio.goc](https://github.com/bluewaysw/pcgeos/tree/master/Library/Breadbox/CDAudio/cdaudio.goc#L190) and it looks like the code that does the actual version check is turned off via preprocessor (wrapped in `#if 0` / `#endif`).

/cdaudio.goc

**Comment by coldacid** [comment]
I wonder if cdaudio.goc could be simplified by moving away from all the inline ASM towards use of i86.h int* functions. I'm not at all clear on how the code that's in there now (including what's been ifdeffed out) actually ends up calling on interrupt 2Fh with the appropriate values for the [MSCDEX commands](https://makbit.com/articles/mscdex.txt) (AH=15h, AL as appropriate).

For example, lines 198-203 are currently

```c
    asm {
      push di
      mov  di,8         /* get number of drives */
      } CallCDDriver(); asm {
      pop  di
      mov  MSCDEX_CD_Drives,al
    }
```

Based on the comment in the code, this could be just calling INT 2Fh with AX=1500h, and storing the value of BX into `MSCDEX_CD_Drives` after the interrupt handler returns to us. Then we have

```c
      asm {
        push di
        mov  di, 10          /* get MSCDEX version number */
        } CallCDDriver(); asm {
        mov  MSCDEX_Version,ax
        mov  ax, segm
        mov  bx, offs
        mov  di, 12          /* get CD drive letters */
        } CallCDDriver(); asm {
        pop  di
      }
```

which would be two calls to interrupt 2Fh:

1. AX=150Ch, BX=0 in; BX out to `MSCDEX_Version`
2. AX=150Dh, ES:BX=far pointer to `MSCDEX_Drive_Letters` in; no out

There's something magical about CallCDDriver() that I'm just not getting...

**Comment by bluewaysw** [comment]
Thank you for bringing this up and looking into it!
Looks like there is some work left to complete the port to the new FreeGEOS tools using WATCOM.

Yes the #if 0/#endif blocks need to be ported and tested but also the CallCDDriver() function missing relevant functionality.  The original code looks like this:

```
void CallCDDriver (void)
{
  DriverInfoStruct * driverInfo;
  int segm;
  int offs;
  asm {
    push ds
    push si
    push ax
    push bx
    push cx
    push dx
    push di
  }
  driverInfo = GeodeInfoDriver(cdDriverHandle);
  segm = FP_SEG(driverInfo) ;
  offs = FP_OFF(driverInfo) ;
  asm {
    pop  di
    pop  dx
    pop  cx
    pop  bx
    pop  ax
    mov  si, offs
    mov  ds, segm
//    DB   03eh, 0ffh, 01ch	// call far ds:[si]
    DB   0x3e, 0xff, 0x1c	// call far ds:[si]
	 pop  si
    pop  ds
  }
}

```
Maybe a better approach to implement this is to put all those functions that need assembly into a .asm module instead of using the inline assembly approach in C. What do you think?

**Comment by coldacid** [comment]
An .asm module might not be a bad idea, but even then I'm still unclear even seeing the original `CallCDDriver()` driver code how we're calling the MSCDEX API on interrupt 2Fh/AH=15h. (I guess it must be in the CD driver itself somewhere?) 6502 and 68k assembly makes a lot more sense to me than x86 assembly does.

**Comment by coldacid** [comment]
So, it looks like there are three different subprojects handling CD audio at a low level: the Breadbox CDAudio library which the CD Player application uses, the Breadbox CDADOS driver (in Library/Breadbox/CDADOS for some reason) which the CDAudio library uses, and the CDRom library.

Both CDADOS and CDRom include CD audio play routines. The former is essentially just a light wrapper around MSCDEX, while the latter is a little more featured for C interop but essentially doing the same thing at its core (setting up regs and calling INT 2Fh/AH=15h). At this point I don't see any reason why the CDAudio library should even need to exist, other than to provide a C interface for CDADOS. Any functionality in CDAudio beyond that can be implemented as routines inside CDADOS, and/or could be added to CDRom library.

**Comment by bluewaysw** [comment]
Ok, interesting deep dive. There are 2 solutions:
"CD Player" application with "CDRom library", those are the ones that Geoworks created. Those sources are still GEOS 1.x sources and never got ported. (at least the application is)
The other components relate to the Breadbox CD player that is part of Ensemble now, which is subject here. It seems CDAudio Library tries to abstact the CD audio functionality from the acutal technical interface. For me it is a bit unclear why the integration beween the CDAudio Library and the CDADOS is so raw.

**Comment by coldacid** [comment]
We'd have to find Jens-Michael Gross and ask him if he remembers why he did it this way. It's a damn shame that the CDRom library never got ported because it comes across as very well organized and exceptionally documented. The biggest questions for me are why the CDAudio library does things that should be done in the CDADOS driver, and why it needs so much inline assembly to call on it. (I bet the answer to the second question has a lot to do with optimization, though.)

Despite the strange way that CDAudio and CDADOS interact, the fact is they worked before all that inline asm was disabled, so it's probably worth it trying to get them playing nice again versus trying to port the old CDRom library and rework the CD Player application to use it. I just haven't a clue on where to begin doing that...

**Comment by bluewaysw** [comment]
@coldacid yes, I agree with your summary and suggested approach. Ideal would be a setup that offers CD on DOS level and is able to run the debugger swat, so likely with a DOSBOX or the BASEBOX setup. Then checking and fixing the funtionallity interactivly step by step. Alternative approach is to complete the port of missing inline assembly parts and test a binary afterwards in any GEOS setup.

**Comment by bluewaysw** [comment]
I implemented a fix for this issue and tested it when used in BASEBOX. The new target script option GEOS_CDROM_DRIVE may be used to make audio CD (physical or image) available within GEOS. See #394 for details.

**Comment by coldacid** [comment]
@bluewaysw awesome, sorry I ended up not getting to this.
