### ISSUE TITLE
GeoPoint crasht beim Anlegen neuer Folie

### ISSUE THREAD

**Issue by nschulux** [bluewaysw/pcgeos#608]
GeoPoint crasht, sobald man eine neue Folie anlegt.
von Achim

**Comment by HubertHuckevoll** [comment]
Can confirm this. Crreating a new presentation works but actually adding a slide leads to KR-09.

**Comment by nschulux** [comment]
In my case I would add A Text Graphic from Geodraw get a KR-07.

![image](https://github.com/user-attachments/assets/9d2fad05-ce5e-46c5-9200-b1c6c1822288)

But in second test it worked ?

**Comment by rabe-soft** [comment]
![grafik](https://github.com/user-attachments/assets/1deb7cf5-6920-4132-922d-e170a159d41d)
Because of the stupid bug in swat that often the line it highlights is already executed, the error is probably in line 824. vmbh and mh are fine, but evmbh is zero. So the entryPtr structure is probably not initialized.

**Comment by bluewaysw** [comment]
A fix has been merged to master, please double check the isse.

**Comment by nschulux** [comment]
I tested my senario is good no Kr-07 !
